### ISSUE TITLE
Create a Basic Node.js App

### ISSUE THREAD

**Issue by netflixed** [SAPDocuments/Tutorials#3686]
Tutorial URL: https://developers.sap.com/tutorials/cp-node-create-basic-app.html

Please specify the step you are referring to
Step 3
The Programmcode ist missing a closing ' in line 10.
console.log(`myapp listening on port ${port});
should read
console.log(`myapp listening on port ${port}`);
It causes thi error
c:\nodetutorial\myapp\server.js:10
  console.log(`myapp listening on port ${port});
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unterminated template literal
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by maxstreifeneder** [comment]
hey @nextflixed, 

could you please retest? Should be fixed now. 

Cheers,
Max
