### ISSUE TITLE
Create and Deploy HTML5 and SAP Fiori Launchpad Site Modules 

### ISSUE THREAD

**Issue by yuvione** [SAPDocuments/Tutorials#4767]
Step 8 - Test UI on Cloud Foundry.
Unable to start the app from the tile
Log-dbg.js:456 2020-03-15 10:40:27.350780 Failed to load UI5 component for navigation intent #TravelProcessor-display - Error: adding object "component" with duplicate id 'application-TravelProcessor-display-component'
Error: Error: adding object "component" with duplicate id 'application-TravelProcessor-display-component'
    at O (https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:555:337)
    at f.register (https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:555:553)
    at https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:349:867
    at f.constructor (https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:349:1036)
    at f.constructor (https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:627:577)
    at f.constructor (https://sapui5.hana.ondemand.com/resources/sap/ui/core/library-preload.js?eval:994:323)
    at f.constructor (https://sapui5.hana.ondemand.com/resources/sap/suite/ui/generic/template/lib/AppComponent.js?eval:7:11569)
    at new f (https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:576:558)
    at A (https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:662:472)
    at https://sapui5.hana.ondemand.com/resources/sap-ui-core.js:662:1279 sap.ushell.renderers.fiori2.Shell.controller

**Comment by nadiasacara** [comment]
I got the exact same error today.

**Comment by raz-korn** [comment]
Can you share which exact step generated the error? Add a screenshot of the full screen?

**Comment by yuvione** [comment]
Step 8 - Test UI on Cloud Foundry.
![image](https://user-images.githubusercontent.com/29804551/76855781-db418300-681f-11ea-8685-59f08c1b1e3a.png)
when you click on the tile you get the message
![image](https://user-images.githubusercontent.com/29804551/76856128-9e29c080-6820-11ea-913e-61aae1a82758.png)
I have attached a copy of the xs-app.json file.
![image](https://user-images.githubusercontent.com/29804551/76856161-b0a3fa00-6820-11ea-8e67-db49825e6c65.png)

**Comment by mervey45** [comment]
Hi to all, 

thank you for your messages. We will update this issue. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by s0004403365** [comment]
Hi, I got the exact same error today.  Can you reopen the issue? 

thanks in advance.
