### ISSUE TITLE
Create an Application for Producing Messages

### ISSUE THREAD

**Issue by sbarzaghialteaup** [SAPDocuments/Tutorials#6022]
Tutorial URL: https://developers.sap.com/tutorials/cp-enterprisemessaging-nodejs-producing-app.html

With the source in step 4 I get the error message:

   2020-10-15T22:48:40.80+0200 [APP/PROC/WEB/0] OUT connected                                                                                2020-10-15T22:48:44.80+0200 [APP/PROC/WEB/0] OUT publishing message number 1 to topic coldchainplatform/customera/gateway1/HU/hu-moved    2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR events.js:174
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR       throw er; // Unhandled 'error' event                                               2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR       ^
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR TypeError: Cannot read property 'address' of null                                        2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at OutgoingStream.mapTargetUnified [as _mapTarget] (/home/vcap/app/node_modules/@sap/xb-msg-env/lib/protocols/amqp-v100-sapmgw.js:103:76)                                                                                      2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at OutgoingStream._write (/home/vcap/app/node_modules/@sap/xb-msg-amqp-v100/lib/model/endpoints.js:1352:31)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at doWrite (_stream_writable.js:415:12)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at writeOrBuffer (_stream_writable.js:399:5)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at OutgoingStream.Writable.write (_stream_writable.js:299:11)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at Timeout.handler [as _onTimeout] (/home/vcap/app/producer.js:47:16)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at ontimeout (timers.js:436:11)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at tryOnTimeout (timers.js:300:5)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at listOnTimeout (timers.js:263:5)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at Timer.processTimers (timers.js:223:10)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR Emitted 'error' event at:
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at errorOrDestroy (internal/streams/destroy.js:107:12)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at onwriteError (_stream_writable.js:430:5)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at onwrite (_stream_writable.js:461:5)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at OutgoingStream._write (/home/vcap/app/node_modules/@sap/xb-msg-amqp-v100/lib/model/endpoints.js:1386:13)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at doWrite (_stream_writable.js:415:12)
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     [... lines matching original stack trace ...]
   2020-10-15T22:48:44.81+0200 [APP/PROC/WEB/0] ERR     at tryOnTimeout (timers.js:300:5)
   2020-10-15T22:48:44.83+0200 [APP/PROC/WEB/0] OUT Exit status 1

Thanks for support

**Comment by pradeeppanda-sap** [comment]
Sorry for coming back to you after such a long time.
 Can you please share the producer.js file ?

regards
Pradeep

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
