### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by ramadasupuli** [SAPDocuments/Tutorials#6242]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html

Please specify the step you are referring to
I am not able to perform STEP 5.  I am getting following error;
user: products-service $ npm install --save-dev sqlite3
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v10.22.1-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> sqlite3@5.0.0 install /home/user/projects/products-service/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/home/user/projects/products-service/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote
+ sqlite3@5.0.0
updated 1 package and audited 120 packages in 3.088s
found 0 vulnerabilities

user: products-service $ cds deploy --to sqlite
[ERROR] Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _loadSqlite (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:9:15)
    at Promise (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:31:20)
    at new Promise (<anonymous>)
    at _new (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:30:10)
    at SQLiteDatabase.acquire (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:156:19)
    at SQLiteDatabase.<anonymous> (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:110:29)

user: products-service $ 

Step 5 details:
Step 5: Deploy the domain model
Let’s deploy the domain model to a database. Now, you will use SQLite, a light-weight file-based database, which fits the needs for local development perfectly.

First, install SQLite to the project. Go to the terminal where your application is running and use CTRL+C to stop the application.

Execute the following command in the terminal:

Shell/BashCopy
npm install --save-dev sqlite3
To initialize the database with the defined domain model, execute the following command in the terminal:

Shell/BashCopy
cds deploy --to sqlite

**Comment by chgeo** [comment]
Duplicate of #6240 .  See there for a workaround.

@iwonahahn : Please close this one.

**Comment by ramadasupuli** [comment]
My issue resolve temporarily by using  unset NODE_PATH so closing this issue
