### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by dheffernan-sap** [SAPDocuments/Tutorials#6256]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html

Hi

I followed the tutorial to the letter. After the command 'npm install --save-dev sqlite3' creates a folder 'node_modules' and I see the sqllite3 module.

But it executes with the following warnings:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v10.22.1-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

then I run the cds command 'cds deploy --to sqlite' and I get an error:

[ERROR] Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _loadSqlite (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:9:15)
    at Promise (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:31:20)
    at new Promise (<anonymous>)
    at _new (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:30:10)
    at SQLiteDatabase.acquire (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:156:19)
    at SQLiteDatabase.<anonymous> (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:110:29)

I did this exercise a month ago and it worked. I created a new DEV space to redo the tutorial and the installation of the sqlite and deploying the domain model no longer works.

Does the tutorial need to be updated?
regards
David

**Comment by iwonahahn** [comment]
Hi, 
Please try the provided solution [here](https://github.com/SAPDocuments/Tutorials/issues/6240#issuecomment-734740827).
Best regards,
Iwona

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
