### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by MichaelSturm** [SAPDocuments/Tutorials#6301]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html

Please specify the step you are referring to:
cds deploy --to sqlite

This statement ends in the following error message:
[ERROR] Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:21:17)
    at new Promise (<anonymous>)
    at _new (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:19:10)
    at SQLiteDatabase.acquire (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:130:19)
    at SQLiteDatabase.begin (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/db/Service.js:48:23)
    at Function.for (/extbin/npm/globals/lib/node_modules/@sap/cds/lib/srv/Transaction.js:47:26)

**Comment by iwonahahn** [comment]
Hi Michael,

Please see the comment in this [issue](https://github.com/SAPDocuments/Tutorials/issues/6242). Maybe this solves your problem and you can continue. Otherwise please get back here.

Best regards,
Iwona

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
