### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by kainattu** [SAPDocuments/Tutorials#6305]
Tutorial URL: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html

i am good so far in this tutorial, but i am getting error when i deploy sqlite db. ( i am trying in Hana trial account Sap Business Studio)

user: products-service $ cds deploy --to sqlite3
[ERROR] Didn't find a deployer module for 'sqlite3'
    at Object.deploy (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/deploy/index.js:79:13)
    at Object.exec (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js:35:28)
    at Module.module.exports.Object.assign._ [as exports] (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js:80:49)
    at Object.<anonymous> (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js:85:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

**Comment by iwonahahn** [comment]
Hi,

Please see the comment in this [issue](https://github.com/SAPDocuments/Tutorials/issues/6242). Maybe this solves your problem and you can continue. Otherwise please get back here.

Best regards,
Iwona

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
