### ISSUE TITLE
Create a User Interface with CAP (SAP HANA Cloud)

### ISSUE THREAD

**Issue by I501000** [SAPDocuments/Tutorials#7151]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-ui.html
--------------------------
When I binding the app to a existing HDI ,run into error ,the error is the following ： would you please help on this ?

user: CapXf4 $ npm start
npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v14.17.6-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> CapXf4@1.0.0 start /home/user/projects/CapXf4
> npx cds run

(node:375) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:375) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
[cds] - model loaded from 3 file(s):

  db/interactions.cds
  srv/Interactions_srv.cds
  node_modules/@sap/cds/common.cds

[cds] - connect to db > hana {}
[cds] - serving CatalogService { at: '/catalog' }

[cds] - launched in: 1.749s
[cds] - server listening on { url: 'http://localhost:4004' }
[ terminate with ^C ]

^C
user: CapXf4 $ npm start
npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v14.17.6-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> CapXf4@1.0.0 start /home/user/projects/CapXf4
> npx cds run

(node:409) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:409) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
[cds] - model loaded from 3 file(s):

  db/interactions.cds
  srv/Interactions_srv.cds
  node_modules/@sap/cds/common.cds

[cds] - connect to db > hana {}
[cds] - serving CatalogService { at: '/catalog' }

[cds] - launched in: 572.83ms
[cds] - server listening on { url: 'http://localhost:4004' }
[ terminate with ^C ]

[cds] - GET /catalog/Interactions_Header?$top=11
[cds] - VError: Found 0 matching services
    at Object.serviceCredentials (/home/user/projects/CapXf4/node_modules/@sap/xsenv/lib/xsservices.js:116:11)
    at singleTenantInstanceManager (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:36:58)
    at credentials4 (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:53:85)
    at /home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:138:9
    at new Promise (<anonymous>)
    at pool4 (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:137:7)
    at Object.acquire (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:193:26)
    at HanaDatabase.acquire (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/Service.js:127:28)
    at HanaDatabase.begin (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/db/Service.js:49:25)
    at HanaDatabase.begin_and_dispatch [as dispatch] (/home/user/projects/CapXf4/node_modules/@sap/cds/lib/srv/Transaction.js:149:38) {
  jse_shortmsg: 'Found 0 matching services',
  jse_info: {},
  id: '1738103',
  level: 'ERROR',
  timestamp: 1636333886409
}
[cds] - GET /catalog/Countries?$top=11
[cds] - VError: Found 0 matching services
    at Object.serviceCredentials (/home/user/projects/CapXf4/node_modules/@sap/xsenv/lib/xsservices.js:116:11)
    at singleTenantInstanceManager (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:36:58)
    at credentials4 (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:53:85)
    at /home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:138:9
    at new Promise (<anonymous>)
    at pool4 (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:137:7)
    at Object.acquire (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:193:26)
    at HanaDatabase.acquire (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/Service.js:127:28)
    at HanaDatabase.begin (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/db/Service.js:49:25)
    at HanaDatabase.begin_and_dispatch [as dispatch] (/home/user/projects/CapXf4/node_modules/@sap/cds/lib/srv/Transaction.js:149:38) {
  jse_shortmsg: 'Found 0 matching services',
  jse_info: {},
  id: '1738103',
  level: 'ERROR',
  timestamp: 1636333917008
}
[cds] - GET /catalog/Interactions_Items?$top=11
[cds] - VError: Found 0 matching services
    at Object.serviceCredentials (/home/user/projects/CapXf4/node_modules/@sap/xsenv/lib/xsservices.js:116:11)
    at singleTenantInstanceManager (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:36:58)
    at credentials4 (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:53:85)
    at /home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:138:9
    at new Promise (<anonymous>)
    at pool4 (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:137:7)
    at Object.acquire (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:193:26)
    at HanaDatabase.acquire (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/Service.js:127:28)
    at HanaDatabase.begin (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/db/Service.js:49:25)
    at HanaDatabase.begin_and_dispatch [as dispatch] (/home/user/projects/CapXf4/node_modules/@sap/cds/lib/srv/Transaction.js:149:38) {
  jse_shortmsg: 'Found 0 matching services',
  jse_info: {},
  id: '1738103',
  level: 'ERROR',
  timestamp: 1636333921832
}
[cds] - GET /catalog/Interactions_Items
[cds] - VError: Found 0 matching services
    at Object.serviceCredentials (/home/user/projects/CapXf4/node_modules/@sap/xsenv/lib/xsservices.js:116:11)
    at singleTenantInstanceManager (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:36:58)
    at credentials4 (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:53:85)
    at /home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:138:9
    at new Promise (<anonymous>)
    at pool4 (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:137:7)
    at Object.acquire (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:193:26)
    at HanaDatabase.acquire (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/Service.js:127:28)
    at HanaDatabase.begin (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/db/Service.js:49:25)
    at HanaDatabase.begin_and_dispatch [as dispatch] (/home/user/projects/CapXf4/node_modules/@sap/cds/lib/srv/Transaction.js:149:38) {
  jse_shortmsg: 'Found 0 matching services',
  jse_info: {},
  id: '1738103',
  level: 'ERROR',
  timestamp: 1636334057875
}
[cds] - GET /catalog/$metadata
[cds] - GET /catalog/Interactions_Header
[cds] - VError: Found 0 matching services
    at Object.serviceCredentials (/home/user/projects/CapXf4/node_modules/@sap/xsenv/lib/xsservices.js:116:11)
    at singleTenantInstanceManager (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:36:58)
    at credentials4 (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:53:85)
    at /home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:138:9
    at new Promise (<anonymous>)
    at pool4 (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:137:7)
    at Object.acquire (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/pool.js:193:26)
    at HanaDatabase.acquire (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/hana/Service.js:127:28)
    at HanaDatabase.begin (/home/user/projects/CapXf4/node_modules/@sap/cds-runtime/lib/db/Service.js:49:25)
    at HanaDatabase.begin_and_dispatch [as dispatch] (/home/user/projects/CapXf4/node_modules/@sap/cds/lib/srv/Transaction.js:149:38) {
  jse_shortmsg: 'Found 0 matching services',
  jse_info: {},
  id: '1738103',
  level: 'ERROR',
  timestamp: 1636334160725
}

**Comment by I501000** [comment]
Resolved, need to move the defaultenv to the root  directory .
