### ISSUE TITLE
Add User Authentication to Your Application (SAP HANA Cloud)

### ISSUE THREAD

**Issue by I501000** [SAPDocuments/Tutorials#7152]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-authentication.html
--------------------------

user: CapXf4 $ cds compile srv/ --to xsuaa
[ERROR] Cannot find module '@sap/cds/bin/utils/write'
Require stack:
- /home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/compile.js
- /home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.compile (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/compile.js:188:17)
    at Object.exec (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js:35:28)
    at Module.exports (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js:80:49)
    at Object.<anonymous> (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js:85:29)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by I501000** [comment]
resoved . npm i -g @sap/cds-dk
